name: bcVote
main: Grotznak.bcVote.bcVote
version: 1.0.0
authors: [Grotznak]
website: http://www.diemamaschimpft.de
depend: [Vault]
description: >
             Vote for day, night, sun or rain
load: startup
commands:
  bcvote:
    description: Vote 
    usage: |
           /<command> - Displays vote information
permissions:
  bcvote.wheather:
    description: Vote for wheather changes.
    default: op
  bcvote.time:
    description: Vote for time changes.
    default: op