name: bcVote
main: Grotznak.bcVote.bcVote
version: 0.6.1

authors:
  - Grotznak

commands:
    vote:
        description: Vote for stuff
        usage: /vote [name]
        aliases: [bcvote]
        permission: bcvote.*
