name: bcVote
main: Grotznak.bcVote.bcVote
version: 0.8.2

authors:
  - Grotznak

commands:
    vote:
        description: vote for stuff
        usage: /<command> [stuff]
        permissions: bcvote.*
